uint8 MAUL = 0
uint8 AUTO = 1
uint8 JOINT = 2
uint8 CALI = 3

uint8 NONE = 0
uint8 HOME = 1
uint8 GROUND = 2
uint8 SLIVER = 3
uint8 GOLD = 4
uint8 EXCHANGE = 5
uint8 VISION = 6

uint8 STOP = 0
uint8 TAKE_SLIVER = 1
uint8 TAKE_GOLD = 2

uint8 DESTINTION = 0
uint8 PROCESS = 1


uint8 control_mode
uint8 control_process
uint8 auto_type
uint8 destination
uint8 process

bool final_push
bool y_lock
bool cali
